config/routes.rb
Multiselect::Application.routes.draw do
  resources :authorbooks

  resources :books

  resources :authors

  root :to => 'authors#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :name

  validates :name, :presence => true

  has_many  :authorbooks
  has_many  :books, :through => :authorbooks
end

app/models/authorbook.rb
class Authorbook < ActiveRecord::Base
  attr_accessible :author_id, :book_id

  belongs_to  :book
  belongs_to  :author
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :name

   validates :name, :presence => true

   has_many  :authorbooks
   has_many  :authors, :through => :authorbooks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authorbooks_controller.rb
class AuthorbooksController < ApplicationController
  # GET /authorbooks
  # GET /authorbooks.json
  def index
    @authorbooks = Authorbook.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authorbooks }
    end
  end

  # GET /authorbooks/1
  # GET /authorbooks/1.json
  def show
    @authorbook = Authorbook.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @authorbook }
    end
  end

  # GET /authorbooks/new
  # GET /authorbooks/new.json
  def new
    @authorbook = Authorbook.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @authorbook }
    end
  end

  # GET /authorbooks/1/edit
  def edit
    @authorbook = Authorbook.find(params[:id])
  end

  # POST /authorbooks
  # POST /authorbooks.json
  def create
    @authorbook = Authorbook.new(params[:authorbook])

    respond_to do |format|
      if @authorbook.save
        format.html { redirect_to @authorbook, notice: 'Authorbook was successfully created.' }
        format.json { render json: @authorbook, status: :created, location: @authorbook }
      else
        format.html { render action: "new" }
        format.json { render json: @authorbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authorbooks/1
  # PUT /authorbooks/1.json
  def update
    @authorbook = Authorbook.find(params[:id])

    respond_to do |format|
      if @authorbook.update_attributes(params[:authorbook])
        format.html { redirect_to @authorbook, notice: 'Authorbook was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @authorbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorbooks/1
  # DELETE /authorbooks/1.json
  def destroy
    @authorbook = Authorbook.find(params[:id])
    @authorbook.destroy

    respond_to do |format|
      format.html { redirect_to authorbooks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    @q = Author.search(params[:q])
   @author = @q.result(distinct: true)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    @all_books = Book.all

    @author_book = @author.authorbooks.build


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    params[:books][:id].each do |book|
      if :book.empty?
        @author.authorbooks.build(:book_id => book)
      end
    end

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authorbooks_helper.rb
module AuthorbooksHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authorbooks/_form.html.erb
<%= form_for(@authorbook) do |f| %>
  <% if @authorbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authorbook.errors.count, "error") %> prohibited this authorbook from being saved:</h2>

      <ul>
      <% @authorbook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author_id %><br />
    <%= f.number_field :author_id %>
  </div>
  <div class="field">
    <%= f.label :book_id %><br />
    <%= f.number_field :book_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authorbooks/edit.html.erb
<h1>Editing authorbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @authorbook %> |
<%= link_to 'Back', authorbooks_path %>

app/views/authorbooks/index.html.erb
<h1>Listing authorbooks</h1>

<table>
  <tr>
    <th>Author</th>
    <th>Book</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authorbooks.each do |authorbook| %>
  <tr>
    <td><%= authorbook.author_id %></td>
    <td><%= authorbook.book_id %></td>
    <td><%= link_to 'Show', authorbook %></td>
    <td><%= link_to 'Edit', edit_authorbook_path(authorbook) %></td>
    <td><%= link_to 'Destroy', authorbook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Authorbook', new_authorbook_path %>

app/views/authorbooks/new.html.erb
<h1>New authorbook</h1>

<%= render 'form' %>

<%= link_to 'Back', authorbooks_path %>

app/views/authorbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Author:</b>
  <%= @authorbook.author_id %>
</p>

<p>
  <b>Book:</b>
  <%= @authorbook.book_id %>
</p>


<%= link_to 'Edit', edit_authorbook_path(@authorbook) %> |
<%= link_to 'Back', authorbooks_path %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <%= fields_for(@author_book) do |ab| %>
  <div class="field">
    <%= ab.label "All Books" %><br />
    <%= collection_select(:books, :id, @all_books, :id, :name, {}, {:multiple => true }) %>
  </div>
  <% end %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<%= search_form_for @q do |f| %>
<%= f.label :books_id_eq, "Books" %>
<%= f.collection_select(:authorbooks_book_id_eq, Book.all, :id, :name) %>
 
<%= f.submit "Filter Pro" %>
<% end %>


<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.name %></td>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @author.name %>
  
  
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.name %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @book.name %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Multiselect</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>